### ISSUE TITLE
"Unable to find compatible target in system image" in Docker image on a second machine

### ISSUE THREAD

**Issue by marius311** [KristofferC/PackageCompilerX.jl#106]
I'm trying to use PackageCompilerX to precompile my package so that it loads faster on mybinder.org. I'm using binder's feature of just running a custom Docker image, whose Dockefile you can see [here](https://github.com/marius311/CMBLensing.jl/blob/36ab76b7e137582d56a0120bac87c27dc7c30a0a/Dockerfile.base). The invokation of PackageCompilerX in particular is [line 91](https://github.com/marius311/CMBLensing.jl/blob/36ab76b7e137582d56a0120bac87c27dc7c30a0a/Dockerfile.base#L91): 

```dockerfile
RUN julia -e 'using PackageCompilerX; create_sysimage([:CMBLensing,:Zygote]; sysimage_path="/home/cosmo/CMBLensing/CMBLensing.so")'
```

When I build the image on my machine (Linux x86_64), this works great and I can load the sysimage just fine. However, when I push this exact Docker image and it gets subsequently used by mybinder.org (I have it set up so mybinder isn't building the image, its using the one I push, so its really the identical image which works on my computer), I get:

```
$ julia -J/home/cosmo/CMBLensing/CMBLensing.so
ERROR: Unable to find compatible target in system image.
```

(FWIW if anyone wanted to actually dig around, this could be reproduced by loading up a binder instance at [this link](https://mybinder.org/v2/gh/marius311/CMBLensing.jl/master?urlpath=lab) then launching a new terminal and running that command.)

I'm wondering if this is expected, or if there's anything I can do to debug / solve this problem. Thanks! 

(And also to say, great work on this package, I was blown away when first-try it completely worked compiling my package and all of its complex dependencies)

**Comment by KristofferC** [comment]
You can try pass `cpu_target="generic"` (quality of generated code might be slightly worse though).

Ref: https://github.com/JuliaLang/julia/issues/27131, https://discourse.julialang.org/t/julia-in-a-vm/12781

**Comment by marius311** [comment]
Yep, that did it, thank you!

**Comment by Go4itOttersoft** [comment]
"ERROR: Unable to find compatible target in system image." I am having the same issue. I think this error message can be more specific. I am using RHEL8 and I used "generic", but still I get the error.
