### ISSUE TITLE
Only put the stdlibs required for the current project in the sysimage when creating an app

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/PackageCompilerX.jl#18]
Ref https://github.com/JuliaLang/julia/issues/33963

**Comment by KristofferC** [comment]
I guess this could be solved in a very ugly way with some string modifications of `sysimage.jl`. Shudder.

**Comment by DilumAluthge** [comment]
Could this be a configurable option?

I personally would always like all stdlibs available in my images. Perhaps there could be a keyword argument or something that I can specify `include_all_stdlibs = true` that will allow me to include all the stdlibs?

**Comment by KristofferC** [comment]
This is when creating executables (or apps) for distributing, not when just making a sysimage for local use.

**Comment by pfitzseb** [comment]
> I guess this could be solved in a very ugly way with some string modifications of sysimage.jl. Shudder.

Or by modifying the AST, which admittedly isn't much better ;)
