### ISSUE TITLE
test on more OS

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/PackageCompilerX.jl#27]
freebsd, arm, windows

**Comment by ffevotte** [comment]
I can report that I successfully performed some tests (building sysimages, not apps) on Windows.

Thanks for your work on this!

**Comment by KristofferC** [comment]
Great! Maybe you could run the tests anf see if they pass as well?

**Comment by KristofferC** [comment]
Windows now also on CI

**Comment by KristofferC** [comment]
Pretty good now with ARM included
