### ISSUE TITLE
ERROR: Unable to find compatible target in system image.

### ISSUE THREAD

**Issue by IanButterworth** [KristofferC/PackageCompilerX.jl#38]
This worked for me first time, but now gives me the following immediately:
```
julia> using PackageCompilerX
julia> create_sysimage(:ObjectDetector, sysimage_path="ObjectDetector.so")
ERROR: Unable to find compatible target in system image.
```
julia 1.3.0

I've also been trying out `compile_incremental` from `PackageCompiler` so maybe that's broken something?

**Comment by KristofferC** [comment]
Make sure to try with the default sysimage (if it has been replaced by PackageCompiler, re-download julia). And also, you can run with `ENV["JULIA_DEBUG"] = "PackageCompilerX` to get some debug outputs that might be useful.

**Comment by IanButterworth** [comment]
Re-downloading julia fixed this. I guess `revert()` didn't fully revert back the sysimage.

Although my precompile statement functions are failing to load, while they run successfully when manually running `precompile.jl`.
```
[ Info: PackageCompilerX: creating system image object file, this might take a while...
┌ Error: failed to execute ObjectDetector.YOLO.v2_tiny_416_COCO(silent=true)
└ @ Main.anonymous none:24
┌ Error: failed to execute ObjectDetector.YOLO.v3_320_COCO(silent=true)
└ @ Main.anonymous none:24
┌ Error: failed to execute ObjectDetector.YOLO.v3_416_COCO(silent=true)
└ @ Main.anonymous none:24
┌ Error: failed to execute ObjectDetector.YOLO.v3_608_COCO(silent=true)
└ @ Main.anonymous none:24
┌ Error: failed to execute ObjectDetector.YOLO.v3_tiny_416_COCO(silent=true)
└ @ Main.anonymous none:24
```
Changing to `silent=false` shows that the functions get half-way through then crash (but I want the silent ones to be precompiled) 

https://github.com/r3tex/ObjectDetector.jl/tree/packagecompilation/dev/compilation

**Comment by KristofferC** [comment]
I must have done a bad search and replace in the docs. https://github.com/KristofferC/PackageCompilerX.jl/commit/7766c7dcfa41f0029f2e8bfb0007dcabff10a4ad fixes that and with https://github.com/r3tex/ObjectDetector.jl/pull/20 I get a sysimage that works.

There are some precompilation statements that don't work from Zygote (might be because Zygote does some crazy stuff) but with the sysimage I get

```jl
julia> using ObjectDetector

julia> @time ObjectDetector.YOLO.v2_tiny_416_COCO(silent=true);
  1.692572 seconds (2.48 M allocations: 348.008 MiB, 7.20% gc time)
```

vs

```jl
julia> @time ObjectDetector.YOLO.v2_tiny_416_COCO(silent=true);
 17.446907 seconds (65.42 M allocations: 3.456 GiB, 4.58% gc time)
```

with default sysimage.

**Comment by IanButterworth** [comment]
awesome! Thanks for fixing, testing and PR-ing! 
It's great news that this works
