### ISSUE TITLE
Documenter doesn't like your link style

### ISSUE THREAD

**Issue by cmcaine** [KristofferC/PackageCompilerX.jl#39]
https://github.com/KristofferC/PackageCompilerX.jl/blame/master/docs/src/apps.md#L245

These links don't appear properly in https://kristofferc.github.io/PackageCompilerX.jl/dev/apps/

**Comment by KristofferC** [comment]
Yep, I noticed but haven't gotten around to fixing yet. Thanks for the reminder.

**Comment by KristofferC** [comment]
https://github.com/KristofferC/PackageCompilerX.jl/commit/83fa8f9a98983c5dd1cfb4aa2b98f883f1a20c14
