### ISSUE TITLE
Question: What if I include stdlibs in the list of packages passed to `create_sysimage`? 

### ISSUE THREAD

**Issue by DilumAluthge** [KristofferC/PackageCompilerX.jl#51]
What happens if I accidentally include a stdlib in the list of packages that I pass to `create_sysimage`?

E.g. if I call `create_sysimage` like this:
```julia
create_sysimage([:MyPackage, :Test]; sysimage_path="ExampleSysimage.so")
```

Will that break anything?

**Comment by KristofferC** [comment]
It shouldn't really make a difference.
