### ISSUE TITLE
Custom sysimage is unusable if I delete my `~/.julia` directory?

### ISSUE THREAD

**Issue by DilumAluthge** [KristofferC/PackageCompilerX.jl#53]
I am able to create a custom sysimage with `create_sysimage` and then load it successfully with `julia -JMyCustomSysimage.so`.

However, if I delete my `~/.julia` directory and then try to run `julia -JMyCustomSysimage.so`, then it does not load.

Is there a way to make a custom sysimage that will still work if I delete my `~/.julia` directory?

I read the documentation on "apps", but I don't think that meets my use case. An app needs to have an entry point defined with the signature:
```julia
Base.@ccallable function julia_main()::Cint
  ...
end
```

But I don't have an entry point. I just want to get to a Julia REPL and use the packages in my sysimage.

**Comment by KristofferC** [comment]
What is the error?

When deleting `.julia` you are deleting source files and you run into the same relocatability discussion that is relevant for "apps".

**Comment by DilumAluthge** [comment]
I already deleted the `.so` file, but I believe that there was an exception thrown but no exception handler was available. The stack trace wasn't super helpful. When I get a chance, I'll rebuild the `.so` file.

> When deleting .julia you are deleting source files and you run into the same relocatability discussion that is relevant for "apps".

Have you solved the relocatability problem for "apps"? If so, could we use the same strategy to make relocatable sysimages?

**Comment by KristofferC** [comment]
You would need to copy all artifacts to some other directory, set the DEPOT_PATH to that directory, make sure all packages used are relocatable etc. Then it should just work, nothing really that can be done from PackageCompiler's side.

**Comment by DilumAluthge** [comment]
I'm going to close this for now as it doesn't seem like there is anything actionable on PackageCompiler's side.
