### ISSUE TITLE
logic regarding replacing default image

### ISSUE THREAD

**Issue by daviehh** [KristofferC/PackageCompilerX.jl#63]
The order of the two `if` may need to be changed? When `replace_default = true`, and `sysimage_path = nothing` (default: `sysimage_path` should be `nothing` when replacing default)

https://github.com/KristofferC/PackageCompilerX.jl/blob/61791fdc8379881654c0175d68e65f92e46d1c8e/src/PackageCompilerX.jl#L228-L240

The first if will overwrite the `sysimage_path` variable:↓
https://github.com/KristofferC/PackageCompilerX.jl/blob/61791fdc8379881654c0175d68e65f92e46d1c8e/src/PackageCompilerX.jl#L228-L235

so the second `if` will always error out with `replace_default = true`:↓
https://github.com/KristofferC/PackageCompilerX.jl/blob/61791fdc8379881654c0175d68e65f92e46d1c8e/src/PackageCompilerX.jl#L236-L240

**Comment by KristofferC** [comment]
Oops, I added that recently without any local testing... Thanks for the report.
