### ISSUE TITLE
Ensure calling `Base.compilecache` before `--output` attempts to call `using`

### ISSUE THREAD

**Issue by vtjnash** [KristofferC/PackageCompilerX.jl#68]
The `--output` step somewhat expects that `Base.compilecache` has already been called from a regular copy of the identical system image first before it encounters a `using` statement. This lets it initialize the image properly (run the `__init__` methods) and thereby reduces divergence from the normally tested configuration of packages. While it'll silently fall back to attempting to load it in-process, the result isn't necessarily pleasant.

(Or probably ideally, this package would bypass calling `using` entirely and just directly call `_require_from_serialized` in the compiler process on the return value of `Base.compilecache` from the helper process as this should yet further limit the opportunity for messy errors and other process noise to potentially slip in and cause divergence.)

**Comment by KristofferC** [comment]
> The --output step somewhat expects that Base.compilecache has already been called from a regular copy of the identical system image first before it encounters a using statement. 

Ironically, I run with `compiled_modules=false` to work around https://github.com/JuliaLang/julia/issues/34076.

**Comment by vtjnash** [comment]
Yeah, you're trying to cause the side-effects from the wrong places.

**Comment by KristofferC** [comment]
Are you saying to use some "wrapper script" that looks something like

```jl
using MyApp

Base.@ccallable julia_main
    MyApp.julia_main()
end
```

and `include` that in the `--output` process instead of having the `Base.@ccallable` inside the package that gets precompiled. Should be an easy change if you think that is better.

**Comment by vtjnash** [comment]
Yes
