### ISSUE TITLE
Error when compiling Images: could not load library "libfftw3-3.dll"

### ISSUE THREAD

**Issue by iuliancioarca** [KristofferC/PackageCompilerX.jl#80]
`create_sysimage([:Images]; sysimage_path="C:\\Julia-1.3.0\\lib\\julia\\ExampleSysimage.dll")
[ Info: PackageCompilerX: creating system image object file, this might take a while...
fatal: error thrown and no exception handler available.
ErrorException("error compiling __init__: could not load library "libfftw3-3.dll"
The specified module could not be found.
`
I haven't included the full error stack, but I found that `libfftw3-3.dll` resides in one of the `artifacts` subfolders:
`C:\Julia-1.3.0\.julia\artifacts\2193a89e52669d43b28c47b83e738b73d6ed7a50\bin`
If I add it to Path it works.
Tested on Windows 10 and Julia 1.3.0.
On Julia 1.3.1 it works.

**Comment by KristofferC** [comment]
> On Julia 1.3.1 it works.

Yes Julia 1.3.1 fixes a bug that is needed.

**Comment by KristofferC** [comment]
https://github.com/KristofferC/PackageCompilerX.jl/commit/b0a0f082064f45b9fe1b5802352b420e561e2099
