### ISSUE TITLE
Sysimage creation fails in Windows

### ISSUE THREAD

**Issue by abx78** [KristofferC/PackageCompilerX.jl#90]
I am following the documentation step-by-step to generate a binary from Julia code on a Windows 10 machine using Julia v1.3.1

The first step works fine:

> C:\X>julia --startup-file=no --trace-compile=app_precompile.jl MyApp.jl "FL_insurance_sample.csv"
> FL_insurance_sample.csv: 90356x4

On the next step when I try to create the sysimage I get this error:

> C:\X>julia --startup-file=no -J"C:\julia-1.3.1\lib\julia\sys.dll" --output-o sys.o custom_sysimage.jl
> 
> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
> Exception: EXCEPTION_ACCESS_VIOLATION at 0x669a4e98 -- uv_write at /workspace/srcdir/libuv\src/win\stream.c:124
> in expression starting at none:0
> uv_write at /workspace/srcdir/libuv\src/win\stream.c:124
> jl_uv_write at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\jl_uv.c:476
> uv_write_async at .\stream.jl:967
> uv_write at .\stream.jl:924
> unsafe_write at .\stream.jl:1007
> #with_output_color#707 at .\gcutils.jl:91
> unknown function (ip: 000000001E27E839)
> #with_output_color at .\tuple.jl:0 [inlined]
> #printstyled#708 at .\util.jl:397 [inlined]
> #printstyled at .\none:0
> _jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
> jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
> display_error at .\client.jl:101
> _jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
> jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
> display_error at .\client.jl:104
> _jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
> jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
> jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
> jl_f__apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:627
> jl_f__apply_latest at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:665
> #invokelatest#1 at .\essentials.jl:709 [inlined]
> invokelatest at .\essentials.jl:708 [inlined]
> exec_options at .\client.jl:289
> _start at .\client.jl:460
> unknown function (ip: 00000000181E0BFA)
> _jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
> jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
> unknown function (ip: 00000000004017DD)
> unknown function (ip: 0000000000401BC5)
> unknown function (ip: 00000000004013DE)
> unknown function (ip: 000000000040151A)
> BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
> RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
> Allocations: 863992 (Pool: 863525; Big: 467); GC: 1

Hit me for any additional info. Thank you

**Comment by KristofferC** [comment]
What is the content of `custom_sysimage.jl` at this point?

**Comment by abx78** [comment]
`custom_sysimage.jl` never gets created

**Comment by KristofferC** [comment]
It is not supposed to be created, you have to create it yourself. 

If you are at this place https://juliacomputing.github.io/PackageCompilerX.jl/dev/devdocs/binaries_part_2/#Create-the-sysimage-1 in the tutorial, you need to create `custom_sysimage.jl` with the content showed there.

**Comment by abx78** [comment]
oh are you maybe talking about the `create_sysimage.jl` file? that is exactly the same as the one in the tutorial.

**Comment by KristofferC** [comment]
Yes.

Ok, can you put

```
Base.reinit_stdio()
```

in the top of the file and try again?

**Comment by abx78** [comment]
Ok, that didn't sort any effect, what fixed it was creating an empty `custom_sysimage.jl` file in the directory. The same instruction that failed initially generated a consistent `sys.o` file!

**Comment by KristofferC** [comment]
Okay but that sysimage will not be good (it will not contain the stuff we want). I mean, the stuff we put in `custom_sysimage.jl` is there for a reason...

**Comment by abx78** [comment]
ahah ok. I thought I was going somewhere :) not in a good place apparently

**Comment by KristofferC** [comment]
Well, if it works with an empty file, something inside the file must cause it to crash.

If you leave out `--output-o sys.o` and run the same command, does it crash?

What if you only have

```
Base.init_depot_path()
Base.init_load_path()

@eval Module() begin
    Base.include(@__MODULE__, "MyApp.jl")
end # module

empty!(LOAD_PATH)
empty!(DEPOT_PATH)
```

in there?

**Comment by abx78** [comment]
Ok, I start grasping what's going on. First, I got confused by the documentation: at some point talks about `custom_sysimage.jl`, it actually always refers to the `create_sysimage.jl` that it just got created... my bad! 

Following your advice, I edited the `create_sysimage.jl` to the following:

```
Base.init_depot_path()
Base.init_load_path()

@eval Module() begin
    Base.include(@__MODULE__, "MyApp.jl")
    for (pkgid, mod) in Base.loaded_modules
        if !(pkgid.name in ("Main", "Core", "Base"))
            eval(@__MODULE__, :(const $(Symbol(mod)) = $mod))
        end
    end
    for statement in readlines("app_precompile.jl")
	println(statement)
	Base.include_string(@__MODULE__, statement)
    end
end # module

empty!(LOAD_PATH)
empty!(DEPOT_PATH)
```

this prints the list of precompile insturctions. It fails here:
> precompile(Tuple{getfield(Dates, Symbol("##s626#37")), Any, Any, Any, Any, Any, Any, Any, Any})
> precompile(Tuple{typeof(Dates.character_codes), Type{Dates.DateFormat{Symbol("yyyy-mm-dd"), Tuple{Dates.DatePart{Char(0x79000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x6d000000)}, Dates.Delim{Char, 1}, Dates.DatePart{Char(0x64000000)}}}}})
> ERROR: LoadError: LoadError: Base.CodePointError{UInt32}(0x79000000)
> Stacktrace:
>  [1] code_point_err(::UInt32) at .\char.jl:86
>  [2] Char(::UInt32) at .\char.jl:160
>  [3] top-level scope at string:1
>  [4] include_string(::Module, ::String, ::String) at .\loading.jl:1075
>  [5] include_string at .\loading.jl:1079 [inlined]
>  [6] top-level scope at C:\Temp\compile\PackageCompilerX\create_sysimage.jl:15
> in expression starting at string:1
> in expression starting at C:\Temp\compile\PackageCompilerX\create_sysimage.jl:5

**Comment by KristofferC** [comment]
I thought the `catch` in

```
        try
            Base.include_string(@__MODULE__, statement)
        catch
            # See julia issue #28808
            Core.println("failed to compile statement: ", statement)
        end
```

should take care of that.

**Comment by abx78** [comment]
Now it works. I think it is just my bad understanding of the documentation - I might eventually send a PR clarifying a few things, if that is ok.
