### ISSUE TITLE
Bug: `create_app` doesn’t have the `cpu_target::String` kwarg

### ISSUE THREAD

**Issue by DilumAluthge** [KristofferC/PackageCompilerX.jl#99]
The docstring for `create_app` says that it has the `cpu_target::String` kwarg, but the function doesn’t actually accept that keyword argument.

I think something went wrong when merging #86. Probably because it was during the repository transfer.

cc: @KristofferC

**Comment by KristofferC** [comment]
Oops, I'll fix it in a while unless you beat me to it :)
